/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package onlineshopping;
import java.util.List;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
public class Library {

	public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String [] args) {
    	
    	ApplicationContext context = new ClassPathXmlApplicationContext("springbean.xml");
    	
    	User user = context.getBean("user",User.class);
    	System.out.println("UserName     : " +user.getUsername());
    	System.out.println("Email       : "+user.getEmail());
    	System.out.println("Password        : "+user.getPassword());
    	System.out.println("Shipping Address: "+user.getShipping_address());
    	System.out.println("Billing Address : "+user.getBilling_address());
    	System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
    	
    	Product p1 =(Product) context.getBean("product1");
    	System.out.println("product_name = "+p1.getProduct_name());
	    System.out.println("price = "+p1.getPrice());
	    System.out.println("quantity_in_stock = "+p1.getQuantity_in_stock());
	    System.out.println("imagelocation = "+p1.getImagelocation());
	    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
    	
	    Product p2 =(Product) context.getBean("product2");
    	System.out.println("product_name = "+p2.getProduct_name());
	    System.out.println("price = "+p2.getPrice());
	    System.out.println("quantity_in_stock = "+p2.getQuantity_in_stock());
	    System.out.println("imagelocation = "+p2.getImagelocation());
	    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
	    
	    Product p3 =(Product) context.getBean("product3");
    	System.out.println("product_name = "+p3.getProduct_name());
	    System.out.println("price = "+p3.getPrice());
	    System.out.println("quantity_in_stock = "+p3.getQuantity_in_stock());
	    System.out.println("imagelocation = "+p3.getImagelocation());
	    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
	    
	    Product p4 =(Product) context.getBean("product4");
    	System.out.println("product_name = "+p4.getProduct_name());
	    System.out.println("price = "+p4.getPrice());
	    System.out.println("quantity_in_stock = "+p4.getQuantity_in_stock());
	    System.out.println("imagelocation = "+p4.getImagelocation());
	    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
	    
	    Product p5 =(Product) context.getBean("product5");
    	System.out.println("product_name = "+p5.getProduct_name());
	    System.out.println("price = "+p5.getPrice());
	    System.out.println("quantity_in_stock = "+p5.getQuantity_in_stock());
	    System.out.println("imagelocation = "+p5.getImagelocation());
	    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
	    
	    Product p6 =(Product) context.getBean("product6");
    	System.out.println("product_name = "+p6.getProduct_name());
	    System.out.println("price = "+p6.getPrice());
	    System.out.println("quantity_in_stock = "+p6.getQuantity_in_stock());
	    System.out.println("imagelocation = "+p6.getImagelocation());
	    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
	    
	    Product p7 =(Product) context.getBean("product7");
    	System.out.println("product_name = "+p7.getProduct_name());
	    System.out.println("price = "+p7.getPrice());
	    System.out.println("quantity_in_stock = "+p7.getQuantity_in_stock());
	    System.out.println("imagelocation = "+p7.getImagelocation());
	    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
	    
	    Order order = (Order) context.getBean("order");
	    List<Cart> cartlist = order.getCartlist();
	    int b=1;
	    for(Cart c:cartlist)
	    {
	    	List<Product> pl = c.getProductList();
		    float a = 0;
		    System.out.println("cart = "+b);
		    for( Product p : pl)
		    {
		    	a = a + p.getPrice();
		    	System.out.println("product name = "+ p.getProduct_name());
		    	System.out.println("Price = "+p.getPrice());
		    	System.out.println("Stock = "+p.getQuantity_in_stock());
		    	System.out.println("image location = "+p.getImagelocation());
		    	System.out.println("=========================");
		    }
		    c.setTotal_amount(a);
		    System.out.println("Total amount = "+c.getTotal_amount());
		    System.out.println("Status = "+c.isStatus());
		    System.out.println("Confirm Order = "+c.isConfirmOrder());
		    System.out.println("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_");
		    b++;
	    }
	    
}
}
